name: anybase
description: "The AnyBase App Frontend(A cognitive TranslationLXP)"

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^24.1.41
  docx_to_text: ^1.0.1
  flutter_tts: ^3.8.3
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true

  fonts:
      - family: OpenDyslexic
        fonts:
        - asset: assets/fonts/OpenDyslexic-Regular.otf
        - asset: assets/fonts/OpenDyslexic-Bold.otf
          weight: 700